[package]
name = "hessra"
version = "0.1.0"
edition = "2021"

[workspace]
members = ["hessra-macros"]

[dependencies]
hessra-macros = { path = "hessra-macros", version = "0.1.0" }
serde = { version = "1", features = ["derive"] }
reqwest = { version = "0.12", default-features = false, features = ["rustls-tls", "json"] }
h3 = { version = "0.0.6", optional = true }
h3-quinn = { version = "0.0.7", optional = true }
quinn = { version = "0.11", optional = true }
quinn-proto = { version = "0.11", optional = true }
rustls = { version = "0.23", optional = true }
rustls-pemfile = { version = "2.1.2", optional = true }
bytes = { version = "1.0", optional = true }
futures = { version = "0.3", optional = true }

[features]
default = []
http3 = ["h3", "h3-quinn", "quinn", "quinn-proto", "rustls", "rustls-pemfile", "bytes", "futures"]