[package]
name = "hessra"
version = "0.1.0"
edition = "2021"

[workspace]
members = ["hessra-macros"]

[dependencies]
hessra-macros = { path = "hessra-macros", version = "0.1.0" }
serde = { version = "1", features = ["derive"] }
reqwest = { version = "0.12", default-features = false, features = ["rustls-tls", "json"] }