[advisories]
ignore = [
    "RUSTSEC-2025-0022",  # openssl vulnerability, we're using rustls instead
]

# Justification: We're using reqwest with rustls-tls and have disabled default-features 
# which means we're not using native-tls (and therefore not using openssl),
# but it's still in the dependency tree as an optional dependency. 