[package]
name = "hessra-macros"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
syn = { version = "2", features = ["full"] }
quote = "1"
proc-macro2 = "1"
axum = { version = "0.8", optional = true }

[features]
axum = ["dep:axum"]
