name: Build and Publish Extension

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Extension version"
        required: true
        default: "0.1.0"
  # push:
  #   branches: [main]
  #   tags: ["hessra_authz-v*"] # Only trigger on hessra_authz version tags
  # pull_request:
  #   branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        pg-version: [14, 15, 16, 17]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install pg-trunk
        run: cargo install pg-trunk

      - name: Build Extension
        working-directory: hessra-pgrx/hessra_authz
        run: trunk build --version ${{ github.event.inputs.version || '0.1.0' }} --pg-version ${{ matrix.pg-version }}

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: extension-package
          path: hessra-pgrx/hessra_authz/.trunk/hessra_authz-*.tar.gz
          if-no-files-found: error

      # Only run on tag pushes with the right format - commented out for manual testing
      # - name: Extract version from tag
      #   if: startsWith(github.ref, 'refs/tags/hessra_authz-v')
      #   id: get_version
      #   run: echo "VERSION=${GITHUB_REF#refs/tags/hessra_authz-v}" >> $GITHUB_OUTPUT

      #      - name: Publish to pgt.dev
      #        if: startsWith(github.ref, 'refs/tags/hessra_authz-v')
      #        working-directory: hessra-pgrx/hessra_authz
      #        env:
      #          TRUNK_API_TOKEN: ${{ secrets.TRUNK_API_TOKEN }}
      #          VERSION: ${{ steps.get_version.outputs.VERSION }}
      #        run: |
      #          trunk publish hessra_authz \
      #            --version ${VERSION} \
      #            --description "Postgres Authorization with Local Biscuit Verification — by Hessra" \
      #            --documentation "https://github.com/Hessra-Labs/hessra-sdk.rs/tree/main/hessra-pgrx/hessra_authz" \
      #            --repository "https://github.com/Hessra-Labs/hessra-sdk.rs" \
      #            --license "Apache-2.0" \
      #            --homepage "https://hessra.net" \
      #            --category "security"
